apiVersion: apps/v1
kind: Deployment
metadata:
  name: book-api-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: book-api
  template:
    metadata:
      labels:
        app: book-api
    spec:
      containers:
      - name: book-api
        image: sadi74/bookapi
        ports:
        - containerPort: 8080
